Implement binding std::function
chokobole/node-binding pull request #1
Opened 2020-03-01 07:42 UTC by ntoskrnl7

안녕하세요 :)

예전에 facebook에서 알게되서 유용하게 사용하고 있습니다.

  Javascript 함수에 대한 부분이 없어서 간단하게 구현해서 사용중인데 도움이 될까해서 풀리퀘스트하려고 합니다.

Napi::Function클래스에서 다른 클래스의 ToJSValue를 호출하도록 구현하였는데, 매개변수로 Napi::CallbackInfo를 받아들이도록 되어있어서 Napi::Env를 받아들이는 메서드를 추가했습니다.

감사합니다.

2020-03-07 13:33 UTC, chokobole commented
안녕하세요 ㅎㅎ  저도 생각치 못한 feature를 구현해주셔서  너무 감사합니다. 그리고 리뷰가 너무 늦어서 죄송합니다. ㅠ 전체적으로 부탁드릴 점은,
* 마지막 커밋(a8f506f)은 제 맥에서 테스트하니 아래와 같은 오류가 뜨네요 ㅠ 저도 원인은 모르겠지만 이 커밋은 빼는 건 어떻게 생각하시나요?

```bash
> node-binding@1.4.0 pretest /Users/chokobole/Workspace/node-binding
> node ./test/pretest.js

  CXX(target) Release/obj.target/0_function/addon.o
  SOLINK_MODULE(target) Release/0_function.node
  CXX(target) Release/obj.target/1_default_argument/addon.o
  SOLINK_MODULE(target) Release/1_default_argument.node
  CXX(target) Release/obj.target/2_constructor/addon.o
  SOLINK_MODULE(target) Release/2_constructor.node
  CXX(target) Release/obj.target/3_instance_accessor/addon.o
  SOLINK_MODULE(target) Release/3_instance_accessor.node
  CXX(target) Release/obj.target/4_instance_method/addon.o
  SOLINK_MODULE(target) Release/4_instance_method.node
  CXX(target) Release/obj.target/5_static_method/addon.o
  SOLINK_MODULE(target) Release/5_static_method.node
  CXX(target) Release/obj.target/6_stl/addon.o
  SOLINK_MODULE(target) Release/6_stl.node


> node-binding@1.4.0 test /Users/chokobole/Workspace/node-binding
> mocha

/Users/chokobole/Workspace/node-binding/node_modules/yargs/yargs.js:1163
      else throw err
           ^

Error: dlopen(/Users/chokobole/Workspace/node-binding/test/0_function/build/Release/0_function.node, 1): no suitable image found.  Did find:
        /Users/chokobole/Workspace/node-binding/test/0_function/build/Release/0_function.node: code signature in (/Users/chokobole/Workspace/node-binding/test/0_function/build/Release/0_function.node) not valid for use in process using Library Validation: library load denied by system policy
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1025:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/chokobole/Workspace/node-binding/test/test.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/chokobole/Workspace/node-binding/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/chokobole/Workspace/node-binding/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/Users/chokobole/Workspace/node-binding/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/Users/chokobole/Workspace/node-binding/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/chokobole/Workspace/node-binding/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (/Users/chokobole/Workspace/node-binding/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/Users/chokobole/Workspace/node-binding/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/chokobole/Workspace/node-binding/node_modules/yargs/yargs.js:1104:24)
    at Object.parse (/Users/chokobole/Workspace/node-binding/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/chokobole/Workspace/node-binding/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/chokobole/Workspace/node-binding/node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

* 혹시 커밋을 보기좋게 정리해주실 수 있을까요? 예를 들어 1. Add type convertor class for Napi::Function, 2. Add test 이런 식으로 나눌 수 있을 거 같아서요.

* 제 repo 에 .clang-format 이  있어서 git-clang-format 으로 코드 포매팅 부탁드리겠습니다.

2020-03-07 13:42 UTC, chokobole requested changes

2020-03-07 13:42 UTC, chokobole commented on node_binding/type_convertor.h
>    }
제안해주신 것처럼 const Napi::Env& env 이런 함수가 더 맞는 거 같네요 아래와 같은 함수들은 다 지워주시는 게 좋을 거 같아요 ㅎㅎ

```c++
static Napi::Vaule ToJSValue(const Napi::CallbackInfo& info, ...) {
...
}
```

2020-03-07 13:42 UTC, chokobole commented on node_binding/stl.h
> +};
이것 대신에 아래 하나를 남겨도 되지 않나요? void 함수를 return 해도 동작은 하는 거 같더라고요 ?

2020-03-07 13:42 UTC, chokobole commented on node_binding/stl.h
> +        return true;
이 부분은 return value.IsFunction(); 으로 해주시면 좋을 거 같아요~

2020-03-09 12:03 UTC, ntoskrnl7 commented on node_binding/type_convertor.h
>    }
제가 깃 사용하는게 미숙해서 실수가 많았네요 ㅜㅜ

조치 완료해서 글남깁니다.

1. 커밋(a8f506f)은 bash가 없는 윈도우에서 test할 수 있도록 추가했었는데... 생각해보니 git을 설치하면 bash가 자동으로 설치가되네요 ㅎㅎ
그래서 pretest.js를 제거하고, npm script를 Windows환경 지원하도록 추가(e19b133c)했습니다.

2.  삽질 엄청하다가 작업 완료했습니다. 확인해보시고 부족한 부분 있으면 알려주세요. (이거하면서 git 매커니즘이라던가 명령어도 많이 공부하네요 ㅎㅎ)

3. 처음 써보는거라 맞는지는 모르겠으나 코딩 스타일도 적용했습니다.
누가 커밋 전에 clang-format을 적용하는걸 만들어놨길래 이걸로 코드 스타일 맞췄습니다.
https://github.com/andrewseidl/githook-clang-format/blob/master/clang-format.hook
그런데 **@chokobole 님께서 작성하신거랑 약간 스타일이 다른것같기도 한데 확인 부탁드립니다.**

4. 요청하신데로 ToJSValue매서드 인자를 변경(84078086) 했습니다.
(Napi::CallbackInfo에서 Napi::Env는 참조가능하지만 Napi::Env에서 Napi::CallbackInfo를 참조할 수 없으니 추후 뭔가(?) 추가되면서 ToJSValue메서드에서 Napi::CallbackInfo가 필요로할때도 있지않을까하는 혹시나하는 마음에서 @chokobole 님께서 설계하신게 나을것 같다는 생각이 들어서 유지했었습니다.

2020-03-09 12:04 UTC, ntoskrnl7 commented on node_binding/stl.h
> +};
저도 이건 확인했었는데.. 혹시나하는 불안감에 넣었던것이었습니다..

제가 C++ 보단 C랑 어셈블리에 익숙해서 저런 매직(?)코드를 무서워합니다. ㅎㅎ

말씀하신데로 수정완료했습니다.

2020-03-09 12:07 UTC, ntoskrnl7 commented on node_binding/stl.h
> +        return true;
저 부분은 제가 미숙하게 처리하는것보다 누군가가 return true; 대신에 더 디테일한 검사코드를 작성했으면 하는 마음에서 저렇게 해두었습니다. ㅎㅎ

혹시 저렇게 아무런 검사없이 해도 괜찮을까요? 동작하는데는 문제없긴한데 뭔가 걱정이되거든요

2020-03-10 10:45 UTC, chokobole requested changes

2020-03-10 10:45 UTC, chokobole commented on node_binding/stl.h
> +#include <functional>
header 가 중복됐네요 ㅎㅎ

2020-03-10 10:45 UTC, chokobole commented on README.md
> +  return arg0 + arg1; }
README.md 에 있는 코드들은 수정될 필요가 없어 보이는데요 ㅎㅎ

2020-03-10 10:47 UTC, chokobole commented on node_binding/stl.h
> +        return true;
네네 현재로써는 `Napi::Value` 로 테스트할 수 있는 것은 이것밖에 없어 보이네요 ㅠㅠ 할수만 있다면 argument 랑 return type 을 체크하고 싶은데 생각나는 게 없네요 ㅠ

2020-03-10 10:56 UTC, chokobole commented on node_binding/type_convertor.h
>    }
저도 미숙해서요 ㅠㅠ 
1. 네네 테스트는 리눅스랑 맥에서는 잘 되네요 ㅎㅎ
2. git 부분에 대해서는 아직 이번 PR에 대해서 커밋이 8개가 쌓여있는데 이걸 줄여야 할 거 같거든요. 혹시 아래처럼 해보시겠어요? 제가 원하는 것은 2개나 3개의 커밋만 제게 보였으면 좋겠어요 ㅎㅎ

```bash
git checkout -b backup # backup 브랜치 만들어 두시고

git checkout origin/master
git checkout -b temp
git cherry-pick 840780862227b2f117411b2188e96812dd1f8f79 # Add type convertor class for Napi::Function
git cherry-pick e19b133ca80a538986870da330b9441027bf5505 # Add test code
git push origin temp:master -f # temp 에 있는 branch HEAD를 origin/master 에 덮어씌우기
만약에 여기까지 의도한게 맞다면
git branch -D master # master 를 지우고
git checkout -b master # temp branch 로 master 를 덮어씌우기
```

3. clang-format 제쪽에서 보면은 아직 다 적용이 안 된거 같아요?

```bash
$ clang-format --version
clang-format version 9.0.0-2~ubuntu18.04.2 (tags/RELEASE_900/final)

# diff 떠봐서 비교결과
diff --git a/node_binding/macros.h b/node_binding/macros.h
index 47fd2a8..7588ea0 100644
--- a/node_binding/macros.h
+++ b/node_binding/macros.h
@@ -6,7 +6,6 @@
 #define NODE_BINDING_MACROS_H_
 
 #include "napi.h"
-
 #include "node_binding/template_util.h"
 #include "node_binding/type_convertor.h"
 
diff --git a/node_binding/stl.h b/node_binding/stl.h
index 7a90ffb..3ccd245 100644
--- a/node_binding/stl.h
+++ b/node_binding/stl.h
@@ -7,7 +7,6 @@
 
 #include <functional>
 #include <vector>
-#include <functional>
 
 #include "node_binding/type_convertor.h"
 
diff --git a/test/2_constructor/addon.cc b/test/2_constructor/addon.cc
index 9453b97..2141736 100644
--- a/test/2_constructor/addon.cc
+++ b/test/2_constructor/addon.cc
@@ -2,10 +2,9 @@
 // Use of this source code is governed by a BSD-style license that can be
 // found in the LICENSE file.
 
-#include "point.h"
-
 #include "node_binding/constructor.h"
 #include "node_binding/typed_call.h"
+#include "point.h"
 
 class PointJs : public Napi::ObjectWrap<PointJs> {
  public:
```

4. 아 저는 오히려 @ntoskrnl7 하신 접근이 맞다라고 생각이 되서요. 결국 JS 쪽 value 를 바꾸는데  필요한 정보는 `Napi::Env` 면 충분한데 굳이 `Napi::CallbackInfo` 에서 매번 Env() method를 호출하는 것이 낭비라고 생각이되서요.

2020-03-10 10:58 UTC, chokobole commented
그리고 이 프로젝트가 또 [bazel](https://bazel.build/) 로도 빌드가 되고 있는데 전에는 `ToJSValue()` 함수 수정을 examples/ 밑에서도 수정해주시면 좋을 거 같아요.

```bash
$ bazel test -c dbg //...                                   
INFO: Analyzed 9 targets (0 packages loaded, 0 targets configured).
INFO: Found 9 targets and 0 test targets...
ERROR: /home/chokobole/Workspace/node-binding/examples/BUILD:46:1: C++ compilation of rule '//examples:rect_js' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-fr
ame-pointer -g '-std=c++0x' -MD -MF ... (remaining 39 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
examples/rect_js.cc: In member function 'Napi::Value RectJs::GetTopLeft(const Napi::CallbackInfo&)':
examples/rect_js.cc:58:40: error: no matching function for call to 'ToJSValue(const Napi::CallbackInfo&, Point&)'
   return ToJSValue(info, rect_.top_left);
                                        ^
In file included from ./examples/point_js.h:9:0,
                 from ./examples/rect_js.h:7,
                 from examples/rect_js.cc:5:
./node_binding/type_convertor.h:202:13: note: candidate: template<class T> Napi::Value node_binding::ToJSValue(const Napi::Env&, T&&)
 Napi::Value ToJSValue(const Napi::Env& env, T&& value) {
             ^~~~~~~~~
./node_binding/type_convertor.h:202:13: note:   template argument deduction/substitution failed:
examples/rect_js.cc:58:20: note:   cannot convert 'info' (type 'const Napi::CallbackInfo') to type 'const Napi::Env&'
   return ToJSValue(info, rect_.top_left);
                    ^~~~
examples/rect_js.cc: In member function 'Napi::Value RectJs::GetBottomRight(const Napi::CallbackInfo&)':
examples/rect_js.cc:62:44: error: no matching function for call to 'ToJSValue(const Napi::CallbackInfo&, Point&)'
   return ToJSValue(info, rect_.bottom_right);
                                            ^
In file included from ./examples/point_js.h:9:0,
                 from ./examples/rect_js.h:7,
                 from examples/rect_js.cc:5:
./node_binding/type_convertor.h:202:13: note: candidate: template<class T> Napi::Value node_binding::ToJSValue(const Napi::Env&, T&&)
 Napi::Value ToJSValue(const Napi::Env& env, T&& value) {
             ^~~~~~~~~
./node_binding/type_convertor.h:202:13: note:   template argument deduction/substitution failed:
examples/rect_js.cc:62:20: note:   cannot convert 'info' (type 'const Napi::CallbackInfo') to type 'const Napi::Env&'
   return ToJSValue(info, rect_.bottom_right);
                    ^~~~
INFO: Elapsed time: 0.481s, Critical Path: 0.39s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

2020-03-10 11:48 UTC, chokobole commented
아 그리고 commit 하실 때 다른 컴퓨터에서 하셨나봐요?

```bash
git config user.name
git config user.email
```

을 똑같이 해서 해주시겠어요?

2020-03-10 16:26 UTC, closed without merging